### PR TITLE
Misc Changes (closes #2)

### LINKED ISSUE #2: check checksum of downloaded files
javaducks somehow fetched an invalid file today

```
Jan 12 22:56:16 helsinki1 java[2614]: 2024-01-12T22:56:16.461Z  WARN 2614 --- [ool-worker-5222] c.g.b.caffeine.cache.BoundedLocalCache   : Exception thrown during refresh
Jan 12 22:56:16 helsinki1 java[2614]: java.util.concurrent.CompletionException: java.util.zip.ZipException: zip END header not found
Jan 12 22:56:16 helsinki1 java[2614]:         at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncReload$2(CacheLoader.java:200) ~[caffeine-3.1.6.jar!/:3.1.6]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]: Caused by: java.util.zip.ZipException: zip END header not found
Jan 12 22:56:16 helsinki1 java[2614]:         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1315) ~[jdk.zipfs:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1529) ~[jdk.zipfs:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:174) ~[jdk.zipfs:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125) ~[jdk.zipfs:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120) ~[jdk.zipfs:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:475) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at com.seiama.javaducks.service.JavadocService.lambda$new$1(JavadocService.java:82) ~[classes!/:1.0.0-SNAPSHOT]
Jan 12 22:56:16 helsinki1 java[2614]:         at com.github.benmanes.caffeine.cache.CacheLoader.reload(CacheLoader.java:169) ~[caffeine-3.1.6.jar!/:3.1.6]
Jan 12 22:56:16 helsinki1 java[2614]:         at com.github.benmanes.caffeine.cache.CacheLoader.lambda$asyncReload$2(CacheLoader.java:196) ~[caffeine-3.1.6.jar!/:3.1.6]
Jan 12 22:56:16 helsinki1 java[2614]:         ... 7 common frames omitted
Jan 12 22:56:16 helsinki1 java[2614]: 2024-01-12T22:56:16.461Z ERROR 2614 --- [nio-9579-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
Jan 12 22:56:16 helsinki1 java[2614]: java.util.zip.ZipException: invalid loc 2970996 for entry reading
Jan 12 22:56:16 helsinki1 java[2614]:         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2264) ~[jdk.zipfs:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2205) ~[jdk.zipfs:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2155) ~[jdk.zipfs:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at java.base/java.io.InputStream.transferTo(InputStream.java:782) ~[na:na]
Jan 12 22:56:16 helsinki1 java[2614]:         at org.springframework.http.converter.ResourceHttpMessageConverter.writeContent(ResourceHttpMessageConverter.java:149) ~[spring-web-6.0.9.jar!/:6.0.9]
Jan 12 22:56:16 helsinki1 java[2614]:         at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:138) ~[spring-web-6.0.9.jar!/:6.0.9]
Jan 12 22:56:16 helsinki1 java[2614]:         at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:46) ~[spring-web-6.0.9.jar!/:6.0.9]
Jan 12 22:56:16 helsinki1 java[2614]:         at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:225) ~[spring-web-6.0.9.jar!/:6.0.9]
Jan 12 22:56:16 helsinki1 java[2614]:         at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:300) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
```

### PR DESCRIPTION
**Pull request by MiniDigger**
best reviewed individually, can drop stuff if you don't like the changes.

This implements #2 and should also fix the short 500s while updating, since the file is now fully written first before the old file is overridden, reducing the time an partly downloaded file is on the disk.

the banner

duck from https://asciiart.cc/view/12510 
ascii text from https://patorjk.com/software/taag/#p=display&f=Ogre&t=javaducks

### CODE REVIEW

**Comment by MiniDigger** [comment]
played around with graalvm, might be worth to consider to when we put it into a container, makes it only use 47mb of ram and starts in 0.1 seconds
image

File: src/main/java/com/seiama/javaducks/service/JavadocService.java [hunk 1]
```diff
@@ -145,26 +147,64 @@ private void refreshOne(final AppConfiguration.EndpointConfiguration config) {
...
-          final HttpResponse<InputStream> response = this.httpClient.send(
+          final HttpResponse<String> response = this.httpClient.send(
+            HttpRequest.newBuilder()
+              .GET()
+              .uri(hashUri)
+              .header(HttpHeaders.USER_AGENT, USER_AGENT)
+              .build(),
+            HttpResponse.BodyHandlers.ofString()
+          );
+          if (response.statusCode() != 200) {
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]: Can we use constants instead of magic numbers?

File: src/main/java/com/seiama/javaducks/service/JavadocService.java [hunk 2]
```diff
@@ -145,26 +147,64 @@ private void refreshOne(final AppConfiguration.EndpointConfiguration config) {
...
               .build(),
-            HttpResponse.BodyHandlers.ofInputStream()
+            HttpResponse.BodyHandlers.ofByteArray()
           );
-          try (
-            final InputStream is = response.body();
-            final OutputStream os = Files.newOutputStream(versionPath, StandardOpenOption.CREATE, StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING);
-          ) {
-            is.transferTo(os);
+          if (response.statusCode() != 200) {
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]: Can we use constants instead of magic numbers?

File: src/main/java/com/seiama/javaducks/util/HashUtil.java [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+ */
+package com.seiama.javaducks.util;
+
+import java.security.MessageDigest;
+import java.security.NoSuchAlgorithmException;
+
+public final class HashUtil {
+
+  private HashUtil() {
+      // utility class
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/util/HashUtil.java]:
```suggestion
```

**Review by kashike — CHANGES_REQUESTED** [review]

**Comment by MiniDigger** [comment]
somebody needs to figure out how to make checkstyle ignore the aot sourceset

**Review by kashike — APPROVED** [review]

File: src/main/java/com/seiama/javaducks/JavaDucksRuntimeHints.java [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+import org.springframework.context.annotation.Configuration;
+import org.springframework.context.annotation.ImportRuntimeHints;
+
+@Configuration
+@ImportRuntimeHints(JavaDucksRuntimeHints.JavaDucksRuntimeHintsRegistrar.class)
+public class JavaDucksRuntimeHints {
+
+  static class JavaDucksRuntimeHintsRegistrar implements RuntimeHintsRegistrar {
+    @Override
+    public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/JavaDucksRuntimeHints.java]: Your formatting is off for this entire class - please run `build` and fix the checkstyle issues.

File: src/main/java/com/seiama/javaducks/JavaDucksRuntimeHints.java [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+        try {
+            hints.reflection()
+              .registerConstructor(Class.forName("com.github.benmanes.caffeine.cache.SSLR").getDeclaredConstructors()[0], ExecutableMode.INVOKE)
+              .registerConstructor(Class.forName("com.github.benmanes.caffeine.cache.PSR").getDeclaredConstructors()[0], ExecutableMode.INVOKE);
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/JavaDucksRuntimeHints.java]: Alphabetical.
```suggestion
              .registerConstructor(Class.forName("com.github.benmanes.caffeine.cache.PSR").getDeclaredConstructors()[0], ExecutableMode.INVOKE)
              .registerConstructor(Class.forName("com.github.benmanes.caffeine.cache.SSLR").getDeclaredConstructors()[0], ExecutableMode.INVOKE);
```

**Review by kashike — CHANGES_REQUESTED** [review]

**Review by kashike — APPROVED** [review]
