### PR TITLE
Fallback to SHA1 hash

### LINKED ISSUE #7: Older releases do not have SHA-256 hashes for JARs
If SHA-256 verification fails, attempt SHA-1 verification.

### PR DESCRIPTION
**Pull request by powercasgamer**
Branch name is misleading :p

This will first try SHA256 and if that fails it will fallback to SHA1.

Closes #7 

Some ideas, 

- Make it configurable (application.yaml)
- Don't log the full exception message (see the TODO:) (So you don't get [this](https://i.imgur.com/8zgmwJv.png) lovely message every time
- Better exception handling possibly with a custom RuntimeException that has some more information?

### CODE REVIEW

File: src/main/java/com/seiama/javaducks/service/JavadocService.java [hunk 1]
```diff
@@ -160,28 +162,21 @@ private void refreshOne(final AppConfiguration.EndpointConfiguration config) {
...
         }
+        if (hashPair == null) {
+          throw new RuntimeException("Could not download hash for " + config.name() + " " + version.name());
+        }
         // check hash
         if (Files.isReadable(versionPath)) {
           try {
-            final String hashOnDisk = MavenHashType.SHA256.algorithm().hash(versionPath).toString();
-            if (hashOnDisk.equals(hash)) {
+            final String hashOnDisk = hashPair.hashType.algorithm().hash(versionPath).toString();
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]:
```suggestion
            final String hashOnDisk = hashPair.type().algorithm().hash(versionPath).toString();
```

File: src/main/java/com/seiama/javaducks/service/JavadocService.java [hunk 2]
```diff
@@ -200,9 +195,9 @@ private void refreshOne(final AppConfiguration.EndpointConfiguration config) {
             LOGGER.warn("Could not update javadoc for {} {}. Couldn't download jar. Url: {}, Status code: {}", config.name(), version.name(), jar, response.getStatusCode());
             continue;
           }
-          final String downloadedHash = MavenHashType.SHA256.algorithm().hash(response.getBody()).toString();
-          if (!downloadedHash.equals(hash)) {
-            LOGGER.warn("Could not update javadoc for {} {}. Hash mismatch. Expected: {}, got: {}", config.name(), version.name(), hash, downloadedHash);
+          final String downloadedHash = hashPair.hashType.algorithm().hash(response.getBody()).toString();
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]:
```suggestion
          final String downloadedHash = hashPair.type().algorithm().hash(response.getBody()).toString();
```

File: src/main/java/com/seiama/javaducks/service/JavadocService.java [hunk 3]
```diff
@@ -160,28 +162,21 @@ private void refreshOne(final AppConfiguration.EndpointConfiguration config) {
...
+        if (hashPair == null) {
+          throw new RuntimeException("Could not download hash for " + config.name() + " " + version.name());
+        }
         // check hash
         if (Files.isReadable(versionPath)) {
           try {
-            final String hashOnDisk = MavenHashType.SHA256.algorithm().hash(versionPath).toString();
-            if (hashOnDisk.equals(hash)) {
+            final String hashOnDisk = hashPair.hashType.algorithm().hash(versionPath).toString();
+            if (hashOnDisk.equals(hashPair.hash)) {
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]:
```suggestion
            if (hashOnDisk.equals(hashPair.hash())) {
```

File: src/main/java/com/seiama/javaducks/service/JavadocService.java [hunk 4]
```diff
@@ -200,9 +195,9 @@ private void refreshOne(final AppConfiguration.EndpointConfiguration config) {
             LOGGER.warn("Could not update javadoc for {} {}. Couldn't download jar. Url: {}, Status code: {}", config.name(), version.name(), jar, response.getStatusCode());
             continue;
           }
-          final String downloadedHash = MavenHashType.SHA256.algorithm().hash(response.getBody()).toString();
-          if (!downloadedHash.equals(hash)) {
-            LOGGER.warn("Could not update javadoc for {} {}. Hash mismatch. Expected: {}, got: {}", config.name(), version.name(), hash, downloadedHash);
+          final String downloadedHash = hashPair.hashType.algorithm().hash(response.getBody()).toString();
+          if (!downloadedHash.equals(hashPair.hash)) {
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]:
```suggestion
          if (!downloadedHash.equals(hashPair.hash())) {
```

File: src/main/java/com/seiama/javaducks/service/JavadocService.java [hunk 5]
```diff
@@ -200,9 +195,9 @@ private void refreshOne(final AppConfiguration.EndpointConfiguration config) {
...
+            LOGGER.warn("Could not update javadoc for {} {}. Hash mismatch. Expected: {}, got: {}", config.name(), version.name(), hashPair.hash, downloadedHash);
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]:
```suggestion
            LOGGER.warn("Could not update javadoc for {} {}. Hash mismatch. Expected: {}, got: {}", config.name(), version.name(), hashPair.hash(), downloadedHash);
```

File: src/main/java/com/seiama/javaducks/service/JavadocService.java [hunk 6]
```diff
@@ -215,10 +210,38 @@ private void refreshOne(final AppConfiguration.EndpointConfiguration config) {
...
   public record Key(
     String project,
     String version
   ) {
   }
+
+  @NullMarked
+  public record MavenHashPair(
+    String hash,
+    MavenHashType hashType
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]:
```suggestion
    MavenHashType type
```

File: src/main/java/com/seiama/javaducks/service/JavadocService.java [hunk 7]
```diff
@@ -215,10 +210,38 @@ private void refreshOne(final AppConfiguration.EndpointConfiguration config) {
...
+    for (final MavenHashType hashType : HASH_TYPES) {
+      final URI hashUri = UriComponentsBuilder.fromUri(jarUri).replacePath(jarUri.getPath() + "." + hashType.extension()).build().toUri();
+      try {
+        final ResponseEntity<String> response = this.restClient.get()
+          .uri(hashUri)
+          .header(HttpHeaders.USER_AGENT, USER_AGENT)
+          .retrieve()
+          .toEntity(String.class);
+        if (response.getStatusCode().is2xxSuccessful() && response.getBody() != null) {
+          LOGGER.debug("Downloaded hash for {}. Url: {} using {}", config.name(), hashUri, hashType);
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]: Include hash type in the message

File: src/main/java/com/seiama/javaducks/service/JavadocService.java [hunk 8]
```diff
@@ -215,10 +210,38 @@ private void refreshOne(final AppConfiguration.EndpointConfiguration config) {
...
+          return new MavenHashPair(response.getBody(), hashType);
+        }
+      } catch (final Exception e) {
+        // TODO: Should we log the full stack trace? Potentially only log the exception message under DEBUG level
+        LOGGER.warn("Could not download hash for {}. Url: {}, Exception: {}: {}", config.name(), hashUri, e.getClass().getName(), e.getMessage());
```
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]: Include hash type in the message

File: src/main/java/com/seiama/javaducks/service/JavadocService.java (hunk 5 above)
Comment (kashike) [inline src/main/java/com/seiama/javaducks/service/JavadocService.java]: Include hash type in the message

**Review by kashike — CHANGES_REQUESTED** [review]

**Review by kashike — APPROVED** [review]
